import Footer from './components/Layout/Footer';
import Navbar from './components/Layout/Navbar';
import './global.css';

export const metadata = {
  title: 'Abexita',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
